/**
 * HAAVN St Village Preston · BTR
 * Complete Cost Stack data from HAAVN_Design_Review_2.html
 * Populated with all line items across all 6 sub-tabs
 */

import type { CostLineItem } from './schema'

// ── CONSTRUCTION COSTS (8 items, $176.6M) ───────────────────────────────
export const HAAVN_CONSTRUCTION: CostLineItem[] = [
  {
    id: 'const-basement',
    label: 'Basement (s)',
    units: 5750,
    baseRate: 3200,
    amount: 18_400_000,
    notes: 'Structure only',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-apartment',
    label: 'Apartment',
    units: 23_100,
    baseRate: 3820,
    amount: 88_200_000,
    notes: 'Residential units',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-coldshell',
    label: 'Cold shell',
    units: 4630,
    baseRate: 2400,
    amount: 11_100_000,
    notes: 'Commercial / retail',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-common',
    label: 'Common area',
    units: 4620,
    baseRate: 2100,
    amount: 9_700_000,
    notes: 'Shared spaces',
    sCurve: 'scurve',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-amenities',
    label: 'Amenities',
    units: 1200,
    baseRate: 3500,
    amount: 4_200_000,
    notes: 'Gym, pool, lounges, etc.',
    sCurve: 'scurve',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2026-06',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-external',
    label: 'External works',
    units: 2333,
    baseRate: 1200,
    amount: 2_800_000,
    notes: 'Landscaping, hardscape',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2026-10',
    endDate: '2027-02',
    gstFree: false,
  },
  {
    id: 'const-demo',
    label: 'Demolition',
    units: 1,
    baseRate: 750_000,
    amount: 750_000,
    notes: 'Site prep',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'const-contingency',
    label: 'Contingency',
    pct: 0.05,
    feeBasis: 'construction',
    amount: 8_800_000,
    notes: '5% of base construction',
    sCurve: 'linear',
    fundedBy: 'blend',
    equityPct: 0.5,
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
]

// ── CONSULTANTS (17 items across 5 groups, $5.7M) ──────────────────────
export const HAAVN_CONSULTANTS: CostLineItem[] = [
  // Architecture (8 items, $1.84M)
  {
    id: 'cons-arch-feasibility',
    label: 'Feasibility DPO',
    amount: 25_000,
    notes: 'Architecture',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preacq',
    startDate: '2025-02',
    endDate: '2025-06',
    gstFree: false,
  },
  {
    id: 'cons-arch-masterplan',
    label: 'Master planning permit',
    amount: 65_000,
    notes: 'Architecture',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2026-03',
    gstFree: false,
  },
  {
    id: 'cons-arch-sketch50',
    label: '50% sketch design',
    amount: 120_000,
    notes: 'Architecture',
    sCurve: 'upfront',
    fundedBy: 'blend',
    equityPct: 0.5,
    phase: 'preconst',
    startDate: '2026-03',
    endDate: '2026-07',
    gstFree: false,
  },
  {
    id: 'cons-arch-sketch100',
    label: '100% sketch design',
    amount: 180_000,
    notes: 'Architecture',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-07',
    endDate: '2026-10',
    gstFree: false,
  },
  {
    id: 'cons-arch-dd50',
    label: '50% design development',
    amount: 200_000,
    notes: 'Architecture',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'cons-arch-consdocs',
    label: 'Construction documentation',
    amount: 480_000,
    notes: 'Architecture',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-09',
    gstFree: false,
  },
  {
    id: 'cons-arch-ca',
    label: 'Construction services (CA)',
    amount: 570_000,
    notes: 'Architecture',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-arch-defects',
    label: 'Defects liability period',
    amount: 200_000,
    notes: 'Architecture',
    sCurve: 'backloaded',
    fundedBy: 'debt',
    phase: 'closeout',
    startDate: '2029-03',
    endDate: '2030-03',
    gstFree: false,
  },

  // Civil & Structural (4 items, $980K)
  {
    id: 'cons-civil-dd',
    label: 'Design development',
    amount: 120_000,
    notes: 'Civil & structural',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'cons-civil-constdraw',
    label: 'Construction drawings',
    amount: 280_000,
    notes: 'Civil & structural',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
  {
    id: 'cons-civil-supervision',
    label: 'Site supervision',
    amount: 380_000,
    notes: 'Civil & structural',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-civil-services',
    label: 'Services & infrastructure',
    amount: 200_000,
    notes: 'Civil & structural',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2025-12',
    gstFree: false,
  },

  // Acoustic (3 items, $75K)
  {
    id: 'cons-acoustic-planning',
    label: 'Planning assessment',
    amount: 18_000,
    notes: 'Acoustic',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2025-09',
    gstFree: false,
  },
  {
    id: 'cons-acoustic-schematic',
    label: 'Schematic design',
    amount: 22_000,
    notes: 'Acoustic',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'cons-acoustic-const',
    label: 'Construction drawings',
    amount: 35_000,
    notes: 'Acoustic',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },

  // Environmental (5 items, $420K)
  {
    id: 'cons-env-arborist',
    label: 'Arborist — planning',
    amount: 12_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-04',
    endDate: '2025-09',
    gstFree: false,
  },
  {
    id: 'cons-env-heritage',
    label: 'Cultural heritage CHMP',
    amount: 35_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-04',
    endDate: '2025-12',
    gstFree: false,
  },
  {
    id: 'cons-env-planner',
    label: 'Town planner — permit',
    amount: 180_000,
    notes: 'Environmental',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2026-03',
    gstFree: false,
  },
  {
    id: 'cons-env-landscape',
    label: 'Landscape architect',
    amount: 165_000,
    notes: 'Environmental',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-env-flooding',
    label: 'Flooding & stormwater mgmt',
    amount: 28_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2026-01',
    gstFree: false,
  },

  // Other Consultants (6 items, $1.87M)
  {
    id: 'cons-other-bim-design',
    label: 'BIM management — design',
    amount: 85_000,
    notes: 'Other',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'cons-other-bim-const',
    label: 'BIM management — construction',
    amount: 120_000,
    notes: 'Other',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-other-surveyor',
    label: 'Building surveyor — BCA review',
    amount: 65_000,
    notes: 'Other',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'cons-other-qs',
    label: 'Quantity surveyor',
    amount: 180_000,
    notes: 'Other',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'allphases',
    startDate: '2026-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-other-interior',
    label: 'Interior designer',
    amount: 580_000,
    notes: 'Other',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'cons-other-btr-ops',
    label: 'Operational consultant (BTR)',
    amount: 500_000,
    notes: 'Other',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-01',
    endDate: '2027-01',
    gstFree: false,
  },
]

// ── STATUTORY (9 items, $4.99M) ─────────────────────────────────────────
export const HAAVN_STATUTORY: CostLineItem[] = [
  {
    id: 'stat-building-fee',
    label: 'Building application fee',
    amount: 180_000,
    notes: 'Fixed',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2026-11',
    gstFree: true,
  },
  {
    id: 'stat-metro-levy',
    label: 'Metropolitan planning levy',
    amount: 120_000,
    notes: 'Fixed',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2026-03',
    endDate: '2026-03',
    gstFree: true,
  },
  {
    id: 'stat-open-space',
    label: 'Open space contribution',
    pct: 0.05,
    feeBasis: 'gdv',
    amount: 750_000,
    notes: '5% of land value',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2026-03',
    endDate: '2026-03',
    gstFree: true,
  },
  {
    id: 'stat-planning-app',
    label: 'Planning application fee',
    amount: 85_000,
    notes: 'Fixed',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2025-06',
    gstFree: true,
  },
  {
    id: 'stat-subdivision',
    label: 'Subdivision costs',
    amount: 45_000,
    notes: 'Variable',
    sCurve: 'backloaded',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2028-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'stat-dev-contrib-res',
    label: 'Dev contribution — residential',
    units: 120,
    baseRate: 28_000,
    amount: 3_360_000,
    notes: '$28k per unit',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2026-11',
    gstFree: true,
  },
  {
    id: 'stat-dev-contrib-com',
    label: 'Dev contribution — commercial',
    units: 850,
    baseRate: 450,
    amount: 382_500,
    notes: '$450 per sqm',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2026-11',
    gstFree: true,
  },
  {
    id: 'stat-asset-bond',
    label: 'Asset protection bond',
    amount: 50_000,
    notes: 'Fixed',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2029-03',
    gstFree: true,
  },
  {
    id: 'stat-tenant-reloc',
    label: 'Tenant relocation',
    amount: 0,
    notes: 'N/A — greenfield',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2025-06',
    gstFree: true,
  },
]

// ── HEADWORKS & ENVIRONMENTAL (10 items, $1.792M) ───────────────────────
export const HAAVN_HEADWORKS: CostLineItem[] = [
  // Utilities (7 items)
  {
    id: 'head-gas',
    label: 'Gas application',
    amount: 18_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-nbn',
    label: 'NBN / comms application',
    amount: 12_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-power',
    label: 'Power — powerline change',
    amount: 280_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
  {
    id: 'head-sewer',
    label: 'Sewer & water — PIC',
    amount: 380_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-09',
    gstFree: false,
  },
  {
    id: 'head-storm',
    label: 'Storm water connection',
    amount: 120_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
  {
    id: 'head-substation-design',
    label: 'Substation — design',
    amount: 65_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-substation-works',
    label: 'Substation — works',
    amount: 420_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-09',
    gstFree: false,
  },

  // Environmental (4 items)
  {
    id: 'head-env-soil',
    label: 'Enviro — soil classification',
    amount: 22_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-02',
    endDate: '2025-06',
    gstFree: false,
  },
  {
    id: 'head-env-psi',
    label: 'Enviro — PSI & sampling',
    amount: 45_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-02',
    endDate: '2025-06',
    gstFree: false,
  },
  {
    id: 'head-env-auditor',
    label: 'Environmental auditor',
    amount: 85_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2026-03',
    gstFree: false,
  },
  {
    id: 'head-env-relocation',
    label: 'Asset relocation — headworks',
    amount: 180_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
]

// ── MANAGEMENT (4 items, $5.19M) ──────────────────────────────────────
export const HAAVN_MANAGEMENT: CostLineItem[] = [
  {
    id: 'mgmt-dev-mgmt',
    label: 'Development management',
    pct: 0.04,
    feeBasis: 'construction',
    amount: 3_000_000,
    notes: '4% of construction',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-project-mgmt',
    label: 'Project management',
    pct: 0.02,
    feeBasis: 'construction',
    amount: 1_500_000,
    notes: '2% of construction',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2026-11',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-accounting',
    label: 'Accounting management',
    units: 120,
    baseRate: 3_667,
    amount: 440_000,
    notes: '$16.5k per unit',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-legal',
    label: 'Legal management',
    units: 120,
    baseRate: 2_083,
    amount: 250_000,
    notes: '$16.5k total',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
]

// ── MARKETING (3 groups, $166.4K) ─────────────────────────────────────
export const HAAVN_MARKETING: CostLineItem[] = [
  // Marketing collateral (4 items)
  {
    id: 'mkt-renders-draft',
    label: 'Marketing — renders drafts',
    amount: 45_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2026-03',
    endDate: '2026-06',
    gstFree: false,
  },
  {
    id: 'mkt-renders-final',
    label: 'Marketing — renders final',
    amount: 85_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'mkt-website',
    label: 'Marketing — website',
    amount: 28_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2026-11',
    gstFree: false,
  },
  {
    id: 'mkt-website-hosting',
    label: 'Marketing — website hosting',
    amount: 8_400,
    notes: 'Collateral',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2026-10',
    endDate: '2029-03',
    gstFree: false,
  },

  // Display suite (optional — not yet costed)
  // Advertising (optional — not yet costed)
]
