/**
 * HAAVN St Village Preston · BTR
 * Complete Cost Stack data from HAAVN_Design_Review_2.html
 * Populated with all line items across all 6 sub-tabs
 */

import type { CostLineItem } from './schema'

// ── CONSTRUCTION COSTS (8 items, $176.6M) ───────────────────────────────
export const HAAVN_CONSTRUCTION: CostLineItem[] = [
  {
    id: 'const-basement',
    label: 'Basement (s)',
    units: 5750,
    baseRate: 3200,
    amount: 18_400_000,
    notes: 'Structure only',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-apartment',
    label: 'Apartment',
    units: 23_100,
    baseRate: 3820,
    amount: 88_200_000,
    notes: 'Residential units',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-coldshell',
    label: 'Cold shell',
    units: 4630,
    baseRate: 2400,
    amount: 11_100_000,
    notes: 'Commercial / retail',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-common',
    label: 'Common area',
    units: 4620,
    baseRate: 2100,
    amount: 9_700_000,
    notes: 'Shared spaces',
    sCurve: 'scurve',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-amenities',
    label: 'Amenities',
    units: 1200,
    baseRate: 3500,
    amount: 4_200_000,
    notes: 'Gym, pool, lounges, etc.',
    sCurve: 'scurve',
    fundedBy: 'equity',
    phase: 'construction',
    startDate: '2026-06',
    endDate: '2027-03',
    gstFree: false,
  },
  {
    id: 'const-external',
    label: 'External works',
    units: 2333,
    baseRate: 1200,
    amount: 2_800_000,
    notes: 'Landscaping, hardscape',
    sCurve: 'linear',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2026-10',
    endDate: '2027-02',
    gstFree: false,
  },
  {
    id: 'const-demo',
    label: 'Demolition',
    units: 1,
    baseRate: 750_000,
    amount: 750_000,
    notes: 'Site prep',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'const-contingency',
    label: 'Contingency',
    pct: 0.05,
    feeBasis: 'construction',
    amount: 8_800_000,
    notes: '5% of base construction',
    sCurve: 'linear',
    fundedBy: 'blend',
    equityPct: 0.5,
    phase: 'construction',
    startDate: '2025-01',
    endDate: '2027-03',
    gstFree: false,
  },
]

// ── CONSULTANTS — CFO catalogue (Cost_Stack_Grouped.xlsx). Category (group) → items.
//    Amounts start blank; the CFO/DM fills them per project. Grouping is by `notes`.
const CONSULTANT_CATALOGUE: [string, string[]][] = [
  ['Acoustic Engineer', ['Planning', 'Schematic', 'Construction']],
  ['Arborist', ['Planning', 'Project Arobrist']],
  ['Architect', ['Feasibility DPO', 'Master Planning DPO', 'Feasibility Permit', 'Master Planning Permit', '50% Sketch Design - Planning Lodgment', '100% Sketch Design – Balance', '50% Design Development - Marketing/GMP', '100% Design Development - Tender', 'Construction Documentation', 'Construction Services']],
  ['Audio Visual', ['Schematic', 'Construction drawings']],
  ['BIM', ['Management | Design Stage', 'Management | Construction Stage']],
  ['Building Surveyor', ['BCA Review', 'Construction']],
  ['Services and Infrastructure Report', ['Town Planning']],
  ['Flooding and Stormwater Management Plan', ['Town Planning']],
  ['Civil Eng', ['Design Development', 'Construction Drawings']],
  ['Cultural Heritage', ['CHMP', 'Project CH Review']],
  ['DDA', ['Town Plannng', 'Design Development']],
  ['Demolition', ['Permit and Documents']],
  ['Enviromental', []],
  ['End of Trip', ['Scope', 'Documentation']],
  ['ESD', ['Town Planning', 'JV3 Green Star']],
  ['Facade Eng', ['Town Planning', 'Design Development', 'Construction Drawings']],
  ['Fire Engineering', ['Schematic', 'FEB', 'FER', 'Construction']],
  ['Geotechnical Engineer', ['Report', 'Acid Sulphate']],
  ['Heritage', ['Town Planning', 'Design Development', 'Construction Services']],
  ['Housing Diversity Report', []],
  ['Hotel Management', ['Feasability', 'Operator Selection']],
  ['Intergrated Comms', ['Schematic', 'Design development', 'Construction']],
  ['Interior Design', ['Schematic', 'Marketing', 'Design Development', 'Construction']],
  ['Investigations', ['HAZMAT testing']],
  ['Land Surveyor', ['Feature & Level Survey', 'Title Re-establishment Survey', 'Plan of Subdivision', 'Subdivision Certification Process']],
  ['Landscape', ['DPO', 'Town Planning Submissiom', 'Design Development', 'Contract Documentation', 'Construction Services', 'Defect Liability Period']],
  ['Legal', ['Head Contracts', 'Sales Contract']],
  ['Project Management', ['Design Stage', 'Construction']],
  ['Quanitiy Surveyor', ['initial Report', 'Monthly Claims']],
  ['Security', ['Scope', 'Documentation']],
  ['Specialist Lighting', ['Schematic', 'Design Development']],
  ['Specialist Engineer', ['FP 1.4', 'Zero Fall', 'Threshold']],
  ['Seismic', ['Report']],
  ['Service Diversion', ['Design', 'Construction Services']],
  ['Services', ['Schematic', 'Design Development', 'Construction Drawings', 'Construction Services']],
  ['Structural Eng', ['Schematic', 'Design Development', 'Construction Drawings', 'Construction Services']],
  ['Superintendent', ['Monthly Reporting']],
  ['Technology', ['Program Writing']],
  ['Temporary Works Engineering', []],
  ['Town Planner', ['Strategy & Approval Process', 'Project Team Appointment & Design Inputs', 'DFP Engagement', 'Lodgement DPO / TP', 'RFI DPO / TPO']],
  ['Traffic Management', ['Town Planning', 'CMP']],
  ['Urban Design', ['Concept & Development Plan Scoping', 'Development Plan Preparation', 'TP Application Support *Refer to Fee Proposal']],
  ['VCAT', ['Expert Witness', 'Legal', 'Town Planner']],
  ['Waste Management', ['Town Planning']],
  ['Way Finding and Signage', ['Scope', 'Documents']],
  ['Wind', ['Town Planing', 'Design Development']],
  ['Contingency', []],
]

const catId = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

// A category with no listed sub-items becomes a single line named after the category.
export const HAAVN_CONSULTANTS: CostLineItem[] = CONSULTANT_CATALOGUE.flatMap(([cat, items]) =>
  (items.length ? items : [cat]).map((label, i): CostLineItem => ({
    id: `cons-${catId(cat)}-${i}`,
    label,
    amount: 0,
    notes: cat,
    sCurve: 'scurve',
    fundedBy: 'equity',
    gstFree: false,
  }))
)

// ── STATUTORY — CFO catalogue (Cost_Stack_Grouped.xlsx). Flat list, amounts blank.
export const HAAVN_STATUTORY: CostLineItem[] = [
  'Asset Protection Bond | Demo',
  'Asset Protection Bond | Construction',
  'Building Application Fee',
  'Metropolitan Planning Levy',
  'Open Space Contribution',
  'Planning Application Fee',
  'Subdivision Costs',
  'Development Contribution | Residential',
  'Development Contribution | Commercial',
  'Tenant Relocation',
].map((label, i): CostLineItem => ({ id: `stat-${i}`, label, amount: 0, notes: '', sCurve: 'scurve', fundedBy: 'equity', gstFree: true }))

// ── HEADWORKS & ENVIRONMENTAL (10 items, $1.792M) ───────────────────────
export const HAAVN_HEADWORKS: CostLineItem[] = [
  // Utilities (7 items)
  {
    id: 'head-gas',
    label: 'Gas application',
    amount: 18_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-nbn',
    label: 'NBN / comms application',
    amount: 12_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-11',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-power',
    label: 'Power — powerline change',
    amount: 280_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
  {
    id: 'head-sewer',
    label: 'Sewer & water — PIC',
    amount: 380_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-09',
    gstFree: false,
  },
  {
    id: 'head-storm',
    label: 'Storm water connection',
    amount: 120_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
  {
    id: 'head-substation-design',
    label: 'Substation — design',
    amount: 65_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'head-substation-works',
    label: 'Substation — works',
    amount: 420_000,
    notes: 'Utility',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-09',
    gstFree: false,
  },

  // Environmental (4 items)
  {
    id: 'head-env-soil',
    label: 'Enviro — soil classification',
    amount: 22_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-02',
    endDate: '2025-06',
    gstFree: false,
  },
  {
    id: 'head-env-psi',
    label: 'Enviro — PSI & sampling',
    amount: 45_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-02',
    endDate: '2025-06',
    gstFree: false,
  },
  {
    id: 'head-env-auditor',
    label: 'Environmental auditor',
    amount: 85_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2025-06',
    endDate: '2026-03',
    gstFree: false,
  },
  {
    id: 'head-env-relocation',
    label: 'Asset relocation — headworks',
    amount: 180_000,
    notes: 'Environmental',
    sCurve: 'upfront',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2027-01',
    endDate: '2027-06',
    gstFree: false,
  },
]

// ── MANAGEMENT (4 items, $5.19M) ──────────────────────────────────────
export const HAAVN_MANAGEMENT: CostLineItem[] = [
  {
    id: 'mgmt-dev-mgmt',
    label: 'Development management',
    pct: 0.04,
    feeBasis: 'construction',
    amount: 3_000_000,
    notes: '4% of construction',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-project-mgmt',
    label: 'Project management',
    pct: 0.02,
    feeBasis: 'construction',
    amount: 1_500_000,
    notes: '2% of construction',
    sCurve: 'scurve',
    fundedBy: 'debt',
    phase: 'construction',
    startDate: '2026-11',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-accounting',
    label: 'Accounting management',
    units: 120,
    baseRate: 3_667,
    amount: 440_000,
    notes: '$16.5k per unit',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
  {
    id: 'mgmt-legal',
    label: 'Legal management',
    units: 120,
    baseRate: 2_083,
    amount: 250_000,
    notes: '$16.5k total',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2025-01',
    endDate: '2029-03',
    gstFree: false,
  },
]

// ── MARKETING (3 groups, $166.4K) ─────────────────────────────────────
export const HAAVN_MARKETING: CostLineItem[] = [
  // Marketing collateral (4 items)
  {
    id: 'mkt-renders-draft',
    label: 'Marketing — renders drafts',
    amount: 45_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'acqplan',
    startDate: '2026-03',
    endDate: '2026-06',
    gstFree: false,
  },
  {
    id: 'mkt-renders-final',
    label: 'Marketing — renders final',
    amount: 85_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2027-01',
    gstFree: false,
  },
  {
    id: 'mkt-website',
    label: 'Marketing — website',
    amount: 28_000,
    notes: 'Collateral',
    sCurve: 'upfront',
    fundedBy: 'equity',
    phase: 'preconst',
    startDate: '2026-10',
    endDate: '2026-11',
    gstFree: false,
  },
  {
    id: 'mkt-website-hosting',
    label: 'Marketing — website hosting',
    amount: 8_400,
    notes: 'Collateral',
    sCurve: 'linear',
    fundedBy: 'equity',
    phase: 'allphases',
    startDate: '2026-10',
    endDate: '2029-03',
    gstFree: false,
  },

  // Display suite (optional — not yet costed)
  // Advertising (optional — not yet costed)
]
